load("//starlark:defs.bzl", "waybill_fixture_cc_module")

waybill_fixture_cc_module(
    name = "waybill_fixture_bazel_lib_05",
    srcs = ["core.cc", "util.cc", "engine.cc"],
    hdrs = ["core.h", "util.h"],
    deps = [
        "//libs/waybill_fixture_bazel_lib_03:waybill_fixture_bazel_lib_03",
        "@waybill_fixture_bazel_lib_epsilon//:waybill_fixture_bazel_lib_epsilon",
    ],
    visibility = ["//visibility:public"],
)
