<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.kusari.waybill.fixture.maven</groupId>
        <artifactId>waybill-fixture-maven-root</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>waybill-fixture-maven-b</artifactId>

    <dependencies>
        <dependency>
            <groupId>dev.kusari.waybill.fixture.maven</groupId>
            <artifactId>waybill-fixture-maven-lib-z</artifactId>
            <version>0.5.3</version>
        </dependency>
        <dependency>
            <groupId>dev.kusari.waybill.fixture.maven</groupId>
            <artifactId>waybill-fixture-maven-lib-shared</artifactId>
        </dependency>
    </dependencies>
</project>
