load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//starlark:defs.bzl", "waybill_fixture_cc_module")

waybill_fixture_cc_module(
    name = "waybill_fixture_bazel_app_06",
    srcs = ["main.cc", "handler.cc"],
    hdrs = ["handler.h", "config.h"],
    deps = [
        "//libs/waybill_fixture_bazel_lib_06:waybill_fixture_bazel_lib_06",
        "//libs/waybill_fixture_bazel_lib_07:waybill_fixture_bazel_lib_07",
        "@waybill_fixture_bazel_lib_zeta//:waybill_fixture_bazel_lib_zeta",
    ],
    visibility = ["//visibility:public"],
)
