load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//starlark:defs.bzl", "waybill_fixture_cc_module")

waybill_fixture_cc_module(
    name = "waybill_fixture_bazel_app_10",
    srcs = ["main.cc", "handler.cc"],
    hdrs = ["handler.h", "config.h"],
    deps = [
        "//libs/waybill_fixture_bazel_lib_10:waybill_fixture_bazel_lib_10",
        "//libs/waybill_fixture_bazel_lib_01:waybill_fixture_bazel_lib_01",
        "@waybill_fixture_bazel_lib_kappa//:waybill_fixture_bazel_lib_kappa",
    ],
    visibility = ["//visibility:public"],
)
