load("//starlark:defs.bzl", "waybill_fixture_cc_module")

waybill_fixture_cc_module(
    name = "waybill_fixture_bazel_lib_04",
    srcs = ["core.cc", "util.cc", "engine.cc"],
    hdrs = ["core.h", "util.h"],
    deps = [
        "//libs/waybill_fixture_bazel_lib_02:waybill_fixture_bazel_lib_02",
        "@waybill_fixture_bazel_lib_delta//:waybill_fixture_bazel_lib_delta",
    ],
    visibility = ["//visibility:public"],
)
