load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//starlark:defs.bzl", "waybill_fixture_cc_module")

waybill_fixture_cc_module(
    name = "waybill_fixture_bazel_app_07",
    srcs = ["main.cc", "handler.cc"],
    hdrs = ["handler.h", "config.h"],
    deps = [
        "//libs/waybill_fixture_bazel_lib_07:waybill_fixture_bazel_lib_07",
        "//libs/waybill_fixture_bazel_lib_08:waybill_fixture_bazel_lib_08",
        "@waybill_fixture_bazel_lib_eta//:waybill_fixture_bazel_lib_eta",
    ],
    visibility = ["//visibility:public"],
)
