load("//starlark:defs.bzl", "waybill_fixture_cc_module")

waybill_fixture_cc_module(
    name = "waybill_fixture_bazel_lib_06",
    srcs = ["core.cc", "util.cc", "engine.cc"],
    hdrs = ["core.h", "util.h"],
    deps = [
        "//libs/waybill_fixture_bazel_lib_04:waybill_fixture_bazel_lib_04",
        "@waybill_fixture_bazel_lib_zeta//:waybill_fixture_bazel_lib_zeta",
    ],
    visibility = ["//visibility:public"],
)
